name: Update Translations 

on:
  workflow_dispatch:
  schedule:
    # At 00:00 on Sunday.
    - cron:  '0 0 * * 0'
  push:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update locales
        run: |
          curl -H 'X-API-KEY: ${{ secrets.TOLGEE_TOKEN }}' 'https://app.tolgee.io/v2/projects/export' -o locales.zip
          unzip -o -d ./src/locales locales.zip

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "chore: update translations"
          base: "release"
          branch: "update-tolgee-translations"
          title: "chore: update translations"
          delete-branch: true
